name: Publish to Maven Central

on:
  release:
    types: [created]
    
jobs:
  publish:
    name: Publish Release Artifacts
    runs-on: ubuntu-latest
    
    steps:
      # Step 2
      # Reguired step 
      - name: Check out the repo 
        uses: actions/checkout@v3

      # Step 4
      # Reguired step
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
  
      # Step 6
      # Reguired step 
      - name: Decode GPG Key
        run: |
          mkdir -p ~/.gradle/
          echo "${{secrets.OSSRH_GPG_SECRET_KEY}}" > ~/.gradle/secring.gpg.b64
          base64 -d ~/.gradle/secring.gpg.b64 > ~/.gradle/secring.gpg
      # Step 7
      # Obviously reguired step 
      - name: Publish package
        # wraped the signing.password with single quotes as the password could contain special characters
        run: ./gradlew publish -Psigning.keyId=${{secrets.OSSRH_GPG_SECRET_KEY_ID}} -Psigning.password='${{secrets.OSSRH_GPG_SECRET_KEY_PASSWORD}}' -Psigning.secretKeyRingFile=$(echo ~/.gradle/secring.gpg) --warn --stacktrace
        env:
          OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
          OSSRH_PASSWORD: ${{secrets.OSSRH_TOKEN}}
