name: Java CI with Gradle
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Restore gradle.properties
      env:
        GRADLE_PROPERTIES: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        mkdir -p ~/.gradle/
        # github
        echo "credentials.password = ${GITHUB_TOKEN}" > ~/.gradle/gradle.properties
        echo "credentials.username = NAVE-COHEN" > ~/.gradle/gradle.properties
        # signin
        echo "sining.password = ${SIGNING_PASSWORD}" > ~/.gradle/gradle.properties
        echo "sining.keyId = ${SIGNING_KEYID}" > ~/.gradle/gradle.properties
        gpg --import ${GPG_SECRET_KEY}
        gpg --export-secret-key -a ${SIGNING_KEYID} > private.key
        echo "signing.secretKeyRingFile = private.key" > ~/.gradle/gradle.properties
        # ossrh
        echo "sonatype.Username = ${OSSRH_USERNAME}" > ~/.gradle/gradle.properties
        echo "sonatype.Password = ${OSSRH_TOKEN}" > ~/.gradle/gradle.properties
        # ossrh
        echo "sonatype.Username = ${OSSRH_TOKEN}" > ~/.gradle/gradle.properties
        echo "sonatype.Password = ${OSSRH_TOKEN}" > ~/.gradle/gradle.properties
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: publish
