name: Java CI with Gradle
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Restore gradle.properties
        env:
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEYID: ${{ secrets.SIGNING_KEYID }}
          GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          # signin
          echo "sining.password = ${SIGNING_PASSWORD}" > ~/.gradle/gradle.properties
          echo "sining.keyId = ${SIGNING_KEYID}" > ~/.gradle/gradle.properties
          echo ${GPG_SECRET_KEY} > secring.gpg
          echo "signing.secretKeyRingFile = secring.gpg" > ~/.gradle/gradle.properties
          # ossrh
          echo "sonatype.Username = ${OSSRH_USERNAME}" > ~/.gradle/gradle.properties
          echo "sonatype.Password = ${OSSRH_TOKEN}" > ~/.gradle/gradle.properties
          ./gradlew publish
